Update ja.json
Iskied/vt2-strings pull request #2
Opened 2022-02-02 10:56 UTC by tyoripoko

2022-02-02 12:21 UTC, Iskied requested changes
Check review

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
You should change `�` this character to `\n`.

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
You should change `�` this character to `\n`.

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
You should change `�` this character to `\n`.

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
You should change `�` this character to `\n`.

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
Syntax error

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
You should change `�` this character to `\n`.

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
Syntax error, check this char `�`

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
Syntax error

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
You should change `�` this character to `\n`.

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
You should change `�` this character to `\n`. Don't change %s to %, this will be crashing the game

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
Do you mean `\"`?

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +    "loading_screen_tip_09": "[$KEY;Player__wield_switch_1 :]キーを押すと、射撃武器に切り替わる。",
Don't change macro string.

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +    "loading_screen_tip_27": "[$KEY;Player__action_one :]キーを長押しすると、近接攻撃をチャージできる。",
Don't change macro string.

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +    "loading_screen_tip_84": "レバースイッチやマップ内の様々な仕掛けは、[$KEY;Player__interact :]キーによって動かすことが出来る。",
Don't change macro string.

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +    "loading_screen_tip_45": "[$KEY;Player__action_one :]で通常攻撃、[$KEY;Player__action_one :]長押しでチャージ攻撃となる。",
Don't change macro string.

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +    "loading_screen_tip_01": "後方または横に移動しながら[$KEY;Player__jump_1 :]を押すことで、敵の攻撃を回避したり、間合いを開くことができる。",
Don't change macro string.

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
Don't change macro string.

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
Don't change macro string.

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
Don't change macro string.

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
Don't change macro string.

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
Don't change macro string.

2022-02-02 12:21 UTC, Iskied commented on translation/ui/ja.json
> +
Don't change macro string.

2022-02-02 14:07 UTC, tyoripoko commented on translation/ui/ja.json
> +    "description_dr_helmet_0011": "「ボガ」とは、バーディンがよく用いるカザリッド語の表現で、「ろうそくを消してトンネルを突然真っ暗にする」を意味する。 ����この鉱夫のヘルメットの名は、弾力性に優れたドワーフ特性のろうそくのしなやかさを指す言葉と同じく「ネバーボガ」と訳される。 ����これまで彼らはその名に忠実だったが、バーディンのろうそくが底を尽いてから
ok

2022-02-02 14:29 UTC, closed without merging

2022-02-03 05:10 UTC, Iskied reviewed
Closed